# Generated by Django 5.2.8 on 2026-05-21 02:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtney', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['page_number', 'id']},
        ),
        migrations.AddField(
            model_name='book',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='failed_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='folder_path',
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='processed_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('scanning', 'scanning'), ('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='total_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='file_path',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='page',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='book_start_page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='page',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'tiff', 'tif', 'png', 'jpg', 'jpeg'])]),
        ),
    ]
