# Generated by Django 5.2.8 on 2026-03-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtney', '0002_seed_agents'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
