# Generated by Django 5.2.8 on 2026-03-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtney', '0003_add_slug_to_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='model',
            field=models.CharField(choices=[('llama3.1', 'Llama 3.1'), ('llama3.2-vision', 'Llama 3.2 Vision'), ('minicpm-v', 'MiniCPM v1'), ('gpt-oss', 'GPT-OSS'), ('glm-ocr', 'GLM-OCR')], max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
