# Generated by Django 5.2.8 on 2026-04-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtney', '0004_alter_agent_model_alter_document_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentprocess',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='processlog',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='party',
            name='role',
            field=models.CharField(blank=True, choices=[('GRANTOR', 'Grantor'), ('GRANTEE', 'Grantee'), ('TRUSTEE', 'Trustee'), ('LENDER', 'Lender')], max_length=7, null=True),
        ),
    ]
